name: Build and upload conda packages
on:
  release:
    types: ['released']
  pull_request: # Packages will be built for every PR, but uploaded only when a release is created
    types: ['opened', 'edited', 'reopened', 'synchronize']
  workflow_dispatch:        # Uncomment line if you also want to trigger action manually

jobs:
  conda_deployment_with_new_tag:
    name: Conda build for CUDA ${{ matrix.cuda-version }}
    runs-on: ubuntu-latest
#    runs-on: [self-hosted, gpu]
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: devtools/conda-envs/build_env.yaml
          auto-activate-base: false
          miniforge-version: latest
          activate-environment: build
          channel-priority: strict
          channels: conda-forge
          conda-remove-defaults: true
      - name: Build conda packages
        run: |
          out_dir=`mktemp -d -t build-XXXXXXXXXX`
          echo "out_dir=${out_dir}" >> $GITHUB_ENV
          conda verify devtools/conda-build/
          conda build devtools/conda-build/ --no-anaconda-upload --output-folder ${out_dir} -c conda-forge
      - name: Upload conda packages
        if: github.event_name == 'release' && github.event.action == 'released'
        run: |
         find ${out_dir} -name '*.conda' -print0 | xargs -0 anaconda --verbose -t ${{ secrets.ANACONDA_TOKEN }} upload  --user ComplexFluidsUAM --label main --force   
          
